# spring.main.web-application-type=servlet
spring.application.name=focused_ai_services
moodle.login.endpoint=/login/token.php
moodle.web.service.endpoint=/webservice/rest/server.php
moodle.external.service=fai_moodle
moodle.admin.api.token=b1387f7d154ec94a34959da7e7a57e0c