-- Add gender column to patient and caregiver tables
ALTER TABLE patient ADD COLUMN gender VARCHAR(20);
ALTER TABLE caregiver ADD COLUMN gender VARCHAR(20);

-- Add comments for gender columns
COMMENT ON COLUMN patient.gender IS 'Patient gender (MALE, FEMALE, OTHER, PREFER_NOT_TO_SAY)';
COMMENT ON COLUMN caregiver.gender IS 'Caregiver gender (MALE, FEMALE, OTHER, PREFER_NOT_TO_SAY)';

-- Create patient_allergy table for storing patient allergies
CREATE TABLE patient_allergy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    allergen VARCHAR(255) NOT NULL,
    allergy_type VARCHAR(50),
    severity VARCHAR(50),
    reaction TEXT,
    notes TEXT,
    diagnosed_date VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_patient_allergy_patient FOREIGN KEY (patient_id) REFERENCES patient(id) ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX idx_patient_allergy_patient_id ON patient_allergy(patient_id);
CREATE INDEX idx_patient_allergy_active ON patient_allergy(patient_id, is_active);
CREATE INDEX idx_patient_allergy_allergen ON patient_allergy(allergen);

-- Add comments for documentation
COMMENT ON TABLE patient_allergy IS 'Patient allergy information including allergens, reactions, and severity';
COMMENT ON COLUMN patient_allergy.patient_id IS 'Reference to the patient who has this allergy';
COMMENT ON COLUMN patient_allergy.allergen IS 'Name of the allergen (e.g., Peanuts, Penicillin, Latex)';
COMMENT ON COLUMN patient_allergy.allergy_type IS 'Type of allergy (FOOD, MEDICATION, ENVIRONMENTAL, CONTACT, SEASONAL, OTHER)';
COMMENT ON COLUMN patient_allergy.severity IS 'Severity level (MILD, MODERATE, SEVERE, LIFE_THREATENING)';
COMMENT ON COLUMN patient_allergy.reaction IS 'Description of allergic reaction symptoms';
COMMENT ON COLUMN patient_allergy.notes IS 'Additional notes from healthcare providers';
COMMENT ON COLUMN patient_allergy.diagnosed_date IS 'When the allergy was first diagnosed';
COMMENT ON COLUMN patient_allergy.is_active IS 'Whether the allergy is currently active (for soft deletes)';
