   # Database Configuration
    spring.datasource.url=jdbc:postgresql://careconnect-db.cbw6u68qs0cv.us-east-2.rds.amazonaws.com:5432/careconnect
    spring.datasource.username=postgres
    spring.datasource.password=
    spring.datasource.driver-class-name=org.postgresql.Driver

    # JPA / Hibernate Configuration
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

    # Optional: Server port (defaults to 8080)
    # server.port=8080

    careconnect.upload.dir=%USERPROFILE%/Documents/uploads
    careconnect.baseurl=http://10.0.2.2:8080

    spring.sql.init.mode=never