-- Create vital_sample table for unified vital signs storage
CREATE TABLE vital_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    heart_rate DOUBLE PRECISION,
    spo2 DOUBLE PRECISION,
    systolic INTEGER,
    diastolic INTEGER,
    weight DOUBLE PRECISION,
    mood_value INTEGER CHECK (mood_value >= 1 AND mood_value <= 10),
    pain_value INTEGER CHECK (pain_value >= 1 AND pain_value <= 10),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vital_sample_patient FOREIGN KEY (patient_id) REFERENCES patient(id) ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX idx_vital_sample_patient_timestamp ON vital_sample(patient_id, timestamp DESC);
CREATE INDEX idx_vital_sample_timestamp ON vital_sample(timestamp DESC);

-- Add comments for documentation
COMMENT ON TABLE vital_sample IS 'Unified storage for all patient vital signs and health measurements';
COMMENT ON COLUMN vital_sample.patient_id IS 'Reference to the patient this vital sample belongs to';
COMMENT ON COLUMN vital_sample.timestamp IS 'When this vital measurement was taken';
COMMENT ON COLUMN vital_sample.heart_rate IS 'Heart rate in beats per minute (BPM)';
COMMENT ON COLUMN vital_sample.spo2 IS 'Blood oxygen saturation percentage (SpO2)';
COMMENT ON COLUMN vital_sample.systolic IS 'Systolic blood pressure in mmHg';
COMMENT ON COLUMN vital_sample.diastolic IS 'Diastolic blood pressure in mmHg';
COMMENT ON COLUMN vital_sample.weight IS 'Patient weight in kilograms';
COMMENT ON COLUMN vital_sample.mood_value IS 'Mood rating on scale 1-10 (1=very bad, 10=excellent)';
COMMENT ON COLUMN vital_sample.pain_value IS 'Pain level on scale 1-10 (1=no pain, 10=severe pain)';
