-- Create patient_medication table for storing patient medications
CREATE TABLE patient_medication (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    medication_name VARCHAR(255) NOT NULL,
    dosage VARCHAR(100),
    frequency VARCHAR(100),
    route VARCHAR(50),
    medication_type VARCHAR(50),
    prescribed_by VARCHAR(255),
    prescribed_date VARCHAR(50),
    start_date VARCHAR(50),
    end_date VARCHAR(50),
    notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_patient_medication_patient FOREIGN KEY (patient_id) REFERENCES patient(id) ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX idx_patient_medication_patient_id ON patient_medication(patient_id);
CREATE INDEX idx_patient_medication_active ON patient_medication(patient_id, is_active);
CREATE INDEX idx_patient_medication_type ON patient_medication(medication_type);
CREATE INDEX idx_patient_medication_name ON patient_medication(medication_name);

-- Add comments for documentation
COMMENT ON TABLE patient_medication IS 'Patient medication information including prescriptions and supplements';
COMMENT ON COLUMN patient_medication.patient_id IS 'Reference to the patient taking this medication';
COMMENT ON COLUMN patient_medication.medication_name IS 'Name of the medication or supplement';
COMMENT ON COLUMN patient_medication.dosage IS 'Dosage information (e.g., 10mg, 2 tablets)';
COMMENT ON COLUMN patient_medication.frequency IS 'How often to take (e.g., twice daily, every 8 hours)';
COMMENT ON COLUMN patient_medication.route IS 'Route of administration (oral, injection, topical, etc.)';
COMMENT ON COLUMN patient_medication.medication_type IS 'Type of medication (PRESCRIPTION, OVER_THE_COUNTER, SUPPLEMENT, HERBAL, EMERGENCY)';
COMMENT ON COLUMN patient_medication.prescribed_by IS 'Name of the prescribing healthcare provider';
COMMENT ON COLUMN patient_medication.prescribed_date IS 'Date when medication was prescribed';
COMMENT ON COLUMN patient_medication.start_date IS 'Date when patient started taking the medication';
COMMENT ON COLUMN patient_medication.end_date IS 'Date when medication should be stopped (null for ongoing)';
COMMENT ON COLUMN patient_medication.notes IS 'Additional instructions or notes about the medication';
COMMENT ON COLUMN patient_medication.is_active IS 'Whether the medication is currently active (for soft deletes)';
