// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with CareConnect app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSZfDwvL4ZYRkEddUyP4adRyvnEMvRvvQ',
    appId: '1:1070028273529:web:d88c7e7069e88454ffa1a8',
    messagingSenderId: '1070028273529',
    projectId: 'careconnectptdemo',
    authDomain: 'careconnectptdemo.firebaseapp.com',
    storageBucket: 'careconnectptdemo.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN7XCaESMDhKwjHQQt8UKQ4-wm4jgP2Sg',
    appId: '1:1070028273529:android:8ecaa6c5160ab941ffa1a8',
    messagingSenderId: '1070028273529',
    projectId: 'careconnectptdemo',
    storageBucket: 'careconnectptdemo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSZfDwvL4ZYRkEddUyP4adRyvnEMvRvvQ',
    appId: '1:1070028273529:ios:d88c7e7069e88454ffa1a8',
    messagingSenderId: '1070028273529',
    projectId: 'careconnectptdemo',
    storageBucket: 'careconnectptdemo.firebasestorage.app',
    iosBundleId: 'com.example.careConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSZfDwvL4ZYRkEddUyP4adRyvnEMvRvvQ',
    appId: '1:1070028273529:ios:d88c7e7069e88454ffa1a8',
    messagingSenderId: '1070028273529',
    projectId: 'careconnectptdemo',
    storageBucket: 'careconnectptdemo.firebasestorage.app',
    iosBundleId: 'com.example.careConnectApp',
  );
}
