spring.application.name=careconnect2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configure the H2 in-memory database
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.platform=h2

# Optional: Enable the H2 console for easy access
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
security.jwt.secret=fh7AhskflKJLh9782jhlkjasd93AkJKLUy098231jkasdAAadf
server.port=8080
jwt.expiration.ms=3600000 # 1 hour in milliseconds

stripe.secret-key=jahgsf_jaskahsgfk
stripe.webhook-secret= whsec_kjhdfkjasf

# --- EMAIL CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bomplar@gmail.com
spring.mail.password=imfp bsrb mlxn weqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true